apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kubectl-run
spec:
  taskRef:
    name: kubernetes-actions
  workspaces:
    - name: kubeconfig-dir
      configMap:
        name: kubeconfig
  params:
    - name: script
      value: |
        kubectl get pods 
        echo "-----------"
        kubectl get deploy
