apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-transaction-purchase
spec:
  workspaces:
    - name: postgres
      description: Workspace for postgres steps.
  params:
    - name: purchased
      description: HTTP-Request transaction validation.
  steps:
    - name: check-transaction-message
      image: alpine
      script: |
        if (( $(params.purchased) )); then
          echo "Purchase transaction was successful."
          # TO-DO: Send a thanking mail to client.
        else
          echo "Purchase transaction was NOT successful. Reporting to Sales Dpt."
          # TO-DO: Report a Slack/Teams/eMail message to 'Sales Dpt.'
        fi
