apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: query-product-stock
spec:
  workspaces:
    - name: postgres
      description: Workspace for postgres steps.
  params:
    - name: hostaddr
      description: PostgreSQL hostname or IP.
      default: "localhost"
    - name: port
      description: PostgreSQL access port.
      default: "5432"
    - name: dbname
      description: PostgreSQL products DB name.
    - name: user
      description: PostgreSQL access user.
    - name: password
      description: PostgreSQL access password.
    - name: id
      description: PostgreSQL product ID to be stock-checked.
  steps:
    - name: query-stock-amount
      image: postgres:12-alpine
      script: |
        #!/bin/bash
        psql "hostaddr=$(params.hostaddr) port=$(params.port) dbname=$(params.dbname) user=$(params.user) password=$(params.password)" > $(workspaces.postgres.path)/products.table << EOF
        SELECT * FROM products;
        EOF
        cat $(workspaces.postgres.path)/products.table
        amount=$(cat $(workspaces.postgres.path)/products.table | grep "^  $(params.id)" | grep -Eo "|[^|]*$" | grep -Eo "[^ ]*")
        if (( amount < 5 )); then
          echo "*Stock seems to be low for the purchased product. Redirecting this event to the re-stock pipeline..."
          # (((Since we are not implementing a re-stock pipeline, you can increase stock manually...)))
        fi
