apiVersion: v1
kind: PersistentVolume
metadata:
  generateName: task-pv-volume-
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: ""
