apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: postgres-backup-restore-pipeline
spec:
  workspaces:
    - name: postgres
      description: Workspace for postgres steps.
  params:
    - name: podname
      description: PostgreSQL pod name to backup.
    - name: dbname
      description: PostgreSQL products DB name.
    - name: user
      description: PostgreSQL access user.
      default: "postgresadmin"
    - name: hostaddr
      description: PostgreSQL hostname or IP.
      default: "localhost"
    - name: port
      description: PostgreSQL access port.
      default: "5432"
    - name: password
      description: PostgreSQL access password.
  tasks:
    - name: postgres-backup
      taskRef:
        name: postgres-backup
      workspaces:
        - name: output
          workspace: postgres
      params:
        - name: podname
          value: "$(params.podname)"
        - name: user
          value: "$(params.user)"
        - name: dbname
          value: "$(params.dbname)"
    - name: postgres-drop
      taskRef:
        name: postgres-drop
      runAfter:
        - postgres-backup
      params:
        - name: hostaddr
          value: "$(params.hostaddr)"
        - name: port
          value: "$(params.port)"
        - name: user
          value: "$(params.user)"
        - name: dbname
          value: "$(params.dbname)"
        - name: password
          value: "$(params.password)"
    - name: postgres-restore
      taskRef:
        name: postgres-restore
      runAfter:
        - postgres-drop
      workspaces:
        - name: backup
          workspace: postgres
      params:
        - name: podname
          value: "$(params.podname)"
        - name: user
          value: "$(params.user)"
        - name: dbname
          value: "$(params.dbname)"
